language: c

compiler:
  - clang
  - gcc

before_install:
  - pass=$(perl -e 'print crypt("password", "testuser")')
  - sudo useradd -m -p "$pass" testuser
  - sudo apt-get update -qq
  - sudo apt-get install -qq php7.2 php7.2-dev libsmbclient-dev samba
  - sudo bash tests/setup-share.sh
  - |
    echo "
    [testshare]
    comment = testshare
    path = /home/testuser/testshare
    guest ok = no
    read only = no
    map archive = yes
    map system = yes
    map hidden = yes
    create mask = 0777
    inherit permissions = yes
    " | sudo tee -a /etc/samba/smb.conf
  - sudo service smbd restart
  - testparm -s
  - ( echo password; echo password ) | sudo smbpasswd -s -a testuser
  - wget https://phar.phpunit.de/phpunit-4.8.9.phar -O phpunit.phar

script:
  - phpize
  - ./configure
  - make
  - sudo make install
  - php --define extension="smbclient.so" phpunit.phar --verbose
